spring.datasource.url=jdbc:mysql://mysql-db:3306/db_favoritos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${MYSQL_ROOT_PASSWORD}

# Comunicación interna entre microservicios en Docker (de favoritos a catalogo)
catalogo.service.url=http://catalogo:8081/catalogo
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.hostname=${spring.application.name}